### PR TITLE
D5300 v102 64mbps hq video patch

### PR DESCRIPTION
**Pull request by joevenzon**
Hello, I looked at the D3300 patch for 64 mbps video, and simply did the same thing for the D5300 at its offsets for firmware 1.0.2. After rebuilding and putting the site up locally, I tested it out on my camera and it worked great. It even still plays back the recorded video fine in the camera.

### CODE REVIEW

**Comment by simeonpilgrim** [comment]
Ah, I can see why you patched the C files for patch tool, but I normally build those from the C# tool via https://github.com/simeonpilgrim/nikon-firmware-tools/tree/master/Nikon-Patch/DumpToC

as I consider the C# files the masters.

**Comment by joevenzon** [comment]
I don't suppose you want to transcribe my changes to the C#? :)

Or if you want me to do it, can you confirm this is the authoritative C# file:
Nikon-Patch\Nikon-Patch\D5300.cs

**Comment by simeonpilgrim** [comment]
If I transcribe them, then it will not be a pull, thus no credit ;-)
But yes, that is the authoritative file.. I have just been looking at the layout (and age of the project files related to "patching" and it's a bit of mess, so was considering refactoring multiple thing. So let me know if you want to transcribe or me it..

**Comment by joevenzon** [comment]
I don't care about the credit, I just wanted people to be able to enjoy higher bitrates. :)

If you don't mind transcribing it, that would be awesome -- I've been busy recently and already spent a lot of time on it this weekend. Just make sure after you do so that the generated C code looks the same -- the D5300 has a couple of 42/35 mbps lines that are different than the 24/20 of the D3300.

**Comment by simeonpilgrim** [comment]
cheers, I will merge your PR anyways, so it's captured, and restructure it at a "low stress" rate.

**Comment by joevenzon** [comment]
Thanks!

**Pull request merged**
