### PR TITLE
D5100 - added patch for Liveview 3 mins --> 6 hours timeout

### PR DESCRIPTION
**Pull request by loneboat**

### CODE REVIEW

**Comment by loneboat** [comment]
This patch gives the D5100 the ability to leave Liveview on for 6 hours, instead of the previous cap of 15 minutes. It does this by modifying the existing "3 min" menu option. Have tested for the last 24 hours without issue.

**Comment by simeonpilgrim** [comment]
Without loading the firmware up, it's at first glance strange that 0xBF -> 0x0F goes from 3min (180s or 180000ms) to 6 hours (21,600s), but I will inspect the change deeper tonight.

**Comment by loneboat** [comment]
Oops, you're correct. This was an artifact from my initial test when I wanted to test whether or not I had found the right value for modifying the time. (16 seconds is much easier/quicker to test than 6 hours!) Feel free to disregard this pull request. I will submit the correct one shortly. Apologies.

**Comment by simeonpilgrim** [comment]
ah, that is how we tested some of these things early on also... no stress. Glad I asked.

**Pull request closed without merging**
