### PR TITLE
First Page of Java Libraries Performance Upgrade 

### PR DESCRIPTION
**Pull request by davidgfb**
First Page of Java Libraries Performance Upgrade using only the needed and necessary libraries

### CODE REVIEW

**Review by vicnevicne — COMMENTED** [review]
Happy to see someone is interested in the Emulator :-). However, I admit don't see the point in specifying the individual classes vs using a wildcard. Agreed, this specific java.awt.Color is clearer than java.awt.*, but for most of the others, what advantage do you see ? Just curious ;-)

**Comment by davidgfb** [comment]
It is a good practice to import only the used modules, not the whole
library. Ex: It is the difference between loading a whole game level vs
only the chunks you’re in.
Just personal preference.

**Comment by vicnevicne** [comment]
> It is a good practice to import only the used modules, not the whole library. Ex: It is the difference between loading a whole game level vs only the chunks you’re in. Just personal preference.

Hmm, except the compiled bytecode is just the same :-), only the source code is different, so _good practice_ is debatable.

Your best argument is "personal preference" :-), and as I'm not involved in this project anymore, I have nothing against your changes.

I'll let Simeon merge them though, because your PR contains changes to the dot net patch tool and I have no experience in that area.

KR. Vicne

**Comment by simeonpilgrim** [comment]
so I am completely not a Java person, but the Java changes seem like a preference thing to me also..

I am however super puzzled by the patcher changes, (and the same "changes" in the prior two PR that were dropped, and am not sure if those are really just you merging the master to your branch, and thus are "not changes" but I am not interested in merging patch changes and Java emulator changes at the same time.

**Comment by davidgfb** [comment]
Yep I tried to update my branch and it gave me errors so I've redone it in a new branch and I noticed I introduced two times manually the same import in "ArmInstructionSet.java"

**Pull request closed without merging**
