### PR TITLE
Try the D5200 no-timeout patch on the D5300 firmware

### PR DESCRIPTION
**Pull request by mdonohue**
I found the same constant in the D5300 firmware file, and in similar
offsets as the D5200 firmware file.  Seems plausible that it will
have the same effect on the D5300.

I don't know how to get this code running, so I can produce a modified firmware.   I'd like to test the output on my D5300

### CODE REVIEW

**Comment by simeonpilgrim** [comment]
> I don't know how to get this code running, so I can produce a modified firmware. I'd like to test the output on my D5300

Download [Visual Studio 2019 Community](https://visualstudio.microsoft.com/downloads/) for free (on Win/Mac) then build all (`Ctrl`+`B`, `Shitf`+`B`) then run (`F5`) the LocalUI tool. Then select "patch firmware" ....

**Comment by simeonpilgrim** [comment]
well having loaded the D5300 1.03 firmware I can confirm those three location are all related to timers that match the Auto Off values..

**Comment by mdonohue** [comment]
Thanks.  I will get visual studio downloaded later tonight and try it out

**Comment by mdonohue** [comment]
Ok, got it running on my laptop, and have the patched firmware installed on my D5300.  Not bricked so far!  I'll follow up in a few days if the 3 hour part works.

**Comment by simeonpilgrim** [comment]
ah, well the value you have patch it too is 27 hours, not 3 that would be `0x80, 0xCB, 0xA4, 0x00`

**Comment by mdonohue** [comment]
> ah, well the value you have patch it too is 27 hours, not 3 that would be `0x80, 0xCB, 0xA4, 0x00`

Even better - I thought 3 hours was a bit short for a "no timeout" option.   The early patch for the D5200 said three hours, so I thought that was still in effect.  I should have actually looked at the number to confirm.

**Comment by EdNutting** [comment]
Can confirm - this works on my Nikon D5300, no problem. I only used the liveview timeout patch - I didn't use the other 64mbps patch.

(Would have saved 30mins if I'd remembered to select "15 min" timeout not "30 min" timeout when verifying the patch worked haha.)

**Comment by mdonohue** [comment]
Thanks Ed.  I've been using this patch for the last 3 weeks - the D5300 is my webcam.   No problems so far with 8-9 hours of usage a day.

**Pull request merged**
